#!/bin/sh

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
FILESJS=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" | sed 's| |\\ |g')
FILECODE=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.html" "*.css" "*.jsx" | sed 's| |\\ |g')
[ -z "$FILESJS" ] && exit 0


PASS=true

printf "\nValidating Javascript:\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi

for FILE in $FILESJS
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    printf "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

printf "\nJavascript validation completed!\n"

if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains FILESJS that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

# Prettify all selected FILESJS
echo "$FILECODE" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified FILESJS to staging
echo "$FILECODE" | xargs git add

exit 0